/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_gov_sus_opendata_dbc_NativeDecompressor */

#ifndef _Included_br_gov_sus_opendata_dbc_NativeDecompressor
#define _Included_br_gov_sus_opendata_dbc_NativeDecompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_gov_sus_opendata_dbc_NativeDecompressor
 * Method:    decompress
 * Signature: (Ljava/lang/String;Lbr/gov/sus/opendata/dbc/NativeDecompressor/DecompressStats;)V
 */
JNIEXPORT void JNICALL Java_br_gov_sus_opendata_dbc_NativeDecompressor_decompress
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     br_gov_sus_opendata_dbc_NativeDecompressor
 * Method:    decompressTo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lbr/gov/sus/opendata/dbc/NativeDecompressor/DecompressStats;)V
 */
JNIEXPORT void JNICALL Java_br_gov_sus_opendata_dbc_NativeDecompressor_decompressTo
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
