name: 'Libdatasus CI'
on:
  workflow_dispatch:
  pull_request:

  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-native-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs && sh ./sh.rustup.rs -y
  build:
    needs: build-native-bridge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven - Unit tests
        run: mvn clean test
